[package]
name = "fusion-ahrs"
version = "0.1.0"
edition = "2024"

[dependencies]
nalgebra = "0.33.2"

[dev-dependencies]
csv = "1.3"
plotters = "0.3"
serde = { version = "1.0", features = ["derive"] }
